#%RAML 1.0 Trait
headers:
  client_id:
    description: Llave del cliente
    required: true
    displayName: Llave del cliente
    type: string
  client_secret:
    description: Llave secreta del cliente
    required: true
    displayName: Llave secreta del cliente
    type: string