#%RAML 1.0 DataType
type: object
properties:
  Nombre:
    type: string
    required: true
  Precio:
    type: number
    required: true
  Tiempo_de_preparacion:
    type: string
    required: false
  Porciones:
    type: number
    required: false
  Imagen:
    type: string
    required: false