#%RAML 1.0 DataType
type: object
properties:
  IdUsuario:
    type: string
    required: true
  Fecha:
    type: string
    required: true
  Hora:
    type: string
    required: true
  Celular:
    type: string
    required: false
  Personas:
    type: number
    required: true
  Tipo_pago:
    type: string
    required: false
  Anotaciones:
    type: string
    required: false