#%RAML 1.0 DataType
type: object
properties:
  OrderId:
    type: string
    required: true
  PayerId:
    type: string
    required: true
  Email:
    type: string
    required: true
  CountryCode:
    type: string
    required: true
  Amount:
    type: string
    required: true
  Currency:
    type: string
    required: true