#%RAML 1.0 DataType
type: object
properties:
  Nombre:
    type: string
    required: true
  Rol:
    type: string
    required: false
  Correo:
    type: string
    required: true
  Direccion:
    type: string
    required: false
  Contrasena:
    type: string
    required: true
  Celular:
    type: string
    required: false