#%RAML 1.0
title: aurelio
description: Proyecto 1
baseUri: http://{host}:{port}/api/
securitySchemes:
  basic:
    type: Basic Authentication
protocols: [http]
securedBy: [basic]
traits:
  hasHeaders: !include traits/hasHeaders.raml
  responses : !include traits/responses.raml

/menu:
  description: Se usa para obtener el menu
  displayName: Panel menu
  get:
    description: Obtener menu
    displayName: Obtener menu
    queryParameters:
      nombre:
        type: string
        required: false
        description: Permite filtrar el menu
    is:
      - hasHeaders
      - responses
    responses:
      200:
        description: OK
        body:
          application/json:
            example: !include examples/menu/menu-get.json
    
  post:
    description: Se usa para crear un menu
    displayName: Crear menu
    body:
      application/json:
        type: !include examples/datatype/menu-dataType.raml
        example: !include examples/datatype/menu-post.json
    is:
      - hasHeaders
      - responses
    responses:
      201:
        description: CREATED
        body:
          application/json:
            example: !include examples/menu/menu-post.json
  
  /{id}:
    delete:
      description: Se usa para eliminar un menu
      displayName: Eliminar menu
      is:
        - hasHeaders
        - responses
      responses:
        200:
          description: OK
          body:
            application/json:
              example: {
                "message" : "Eliminado"
              }
    put:
      description: Se usa para actualizar un menu
      displayName: Actualizar menu
      is:
        - hasHeaders
        - responses
      body:
        application/json:
          type: !include examples/datatype/menu-dataType.raml
          example: !include examples/datatype/menu-post.json
      responses:
        200:
          description: OK
          body:
            application/json:
              example: {
                message : "OK"
              }


/reservar:
  description: Se usa para obtener las reservaciones
  displayName: Panel reservaciones
  get:
    description: Obtener reservacion
    displayName: Obtener reservacion
    queryParameters:
      fecha:
        type: string
        required: false
        description: Permite filtrar las reservaciones
    is:
      - hasHeaders
      - responses
    responses:
      200:
        description: OK
        body:
          application/json:
            example: !include examples/reservar/reservar-get.json
  post:
    description: Se usa para crear reservaciones
    displayName: Crear reservacion
    body:
      application/json:
        type: !include examples/datatype/reservar-dataType.raml
        example: !include examples/datatype/reservar-post.json
    is:
      - hasHeaders
      - responses
    responses:
      201:
        description: CREATED
        body:
          application/json:
            example: !include examples/reservar/reservar-post.json
  /{id}:
    delete:
      description: Se usa para eliminar reservaciones
      displayName: Eliminar reservacion
      is:
        - hasHeaders
        - responses
      responses:
        200:
          description: OK
          body:
            application/json:
              example: {
                "message" : "Eliminado"
              }

/usuarios:
  description: Se usa para obtener usuarios
  displayName: Panel usuarios
  get:
    description: Obtener usuarios
    displayName: Obtener usuarios
    is:
      - hasHeaders
      - responses
    responses:
      200:
        description: OK
        body:
          application/json:
            example: !include examples/usuarios/usuarios-get.json
  post:
    description: Se usa para crear un usuario
    displayName: Crear usuarios
    body:
      application/json:
        type: !include examples/datatype/usuarios-dataType.raml
        example: !include examples/datatype/usuarios-post.json
    is:
      - hasHeaders
      - responses
    responses:
      201:
        description: CREATED
        body:
          application/json:
            example: !include examples/usuarios/usuarios-post.json
  /{id}:
    delete:
      description: Se usa para eliminar un usuario
      displayName: Eliminar usuarios
      is:
        - hasHeaders
        - responses
      responses:
        200:
          description: OK
          body:
            application/json:
              example: {
                "message" : "Eliminado"
              }

/login:
  displayName: Panel Login
  description: Iniciar sesion para usuarios
  is:
    - hasHeaders
    - responses
  post:
    displayName: Iniciar sesion
    description: Se usa para iniciar sesion
    body:
      application/json:
        example: {
          Nombre : "urias",
          Contrasena : "urias"
        }
    responses:
      200:
        description: OK
        body:
          application/json:
            example: {
              "logged" : true,
              "rol" : "Admin"
            }

/ordenes:
  displayName: Panel ordenes
  description: Se usa para obtener las ordenes
  get:
    displayName: Obtener ordenes
    description: se usa para obtener las ordenes activas de los clientes
    is:
      - hasHeaders
      - responses
    queryParameters:
      activas:
        description: Si se desactiva muestra todas las ordenes, incluyendo las inactivas
        displayName: Mostrar inactivas?
        type: string
        required: false
    responses:
      200:
        body:
          application/json:
            example: !include examples/ordenes/ordenes.json
  post:
    description: Se usa para crear ordenes
    displayName: Crear Orden de compra
    is:
      - hasHeaders
      - responses
    body:
      application/json:
        type: !include examples/datatype/ordenes-dataType.raml
        example: !include examples/datatype/ordenes.json
    responses:
      201:
        body:
          application/json:
            example: {
              message : "Orden creada"
            }
  /{id}:
    patch:
      description: Se usa para cambiar el estado de una orden
      displayName: Cambiar estado de orden
      is:
        - hasHeaders
        - responses
      body:
        application/json:
          type: object
          properties:
            Estado:
              type: string
              required: true
          example: {
            "Estado" : "Entregado"
          }
      responses:
        201:
          description: CREATED
          body:
            application/json:
              example: {
                message : "Estado actualizado."
              }