#%RAML 1.0
title: aurelio
description: Proyecto 1
baseUri: http://{host}:{port}/api/
securitySchemes:
  basic:
    type: Basic Authentication
protocols: [http]
securedBy: [basic]
traits:
  hasHeaders: !include traits/hasHeaders.raml
  responses : !include traits/responses.raml

/menu:
  description: Obtener menu
  displayName: Panel menu
  get:
    description: Obtener menu
    displayName: Obtener menu
    queryParameters:
      nombre:
        type: string
        required: false
        description: Permite filtrar el menu
    is:
      - hasHeaders
      - responses
    responses:
      200:
        description: OK
        body:
          application/json:
            example: !include examples/menu/menu-get.json
    
  post:
    description: Crear menu
    displayName: Crear menu
    body:
      application/json:
        type: !include examples/datatype/menu-dataType.raml
        example: !include examples/datatype/menu-post.json
    is:
      - hasHeaders
      - responses
    responses:
      201:
        description: CREATED
        body:
          application/json:
            example: !include examples/menu/menu-post.json
  
  /{id}:
    delete:
      description: Elimina menus
      displayName: Eliminar menu
      is:
        - hasHeaders
        - responses
      responses:
        200:
          description: OK
          body:
            application/json:
              example: {
                "message" : "Eliminado"
              }

/reservar:
  description: Obtener reservacion
  displayName: Panel reservaciones
  get:
    description: Obtener reservacion
    displayName: Obtener reservacion
    queryParameters:
      fecha:
        type: string
        required: false
        description: Permite filtrar las reservaciones
    is:
      - hasHeaders
      - responses
    responses:
      200:
        description: OK
        body:
          application/json:
            example: !include examples/reservar/reservar-get.json
  post:
    description: Crear reservacion
    displayName: Crear reservacion
    body:
      application/json:
        type: !include examples/datatype/reservar-dataType.raml
        example: !include examples/datatype/reservar-post.json
    is:
      - hasHeaders
      - responses
    responses:
      201:
        description: CREATED
        body:
          application/json:
            example: !include examples/reservar/reservar-post.json
  /{id}:
    delete:
      description: Elimina reservaciones
      displayName: Eliminar reservacion
      is:
        - hasHeaders
        - responses
      responses:
        200:
          description: OK
          body:
            application/json:
              example: {
                "message" : "Eliminado"
              }

/usuarios:
  description: Obtener usuarios
  displayName: Panel usuarios
  get:
    description: Obtener usuarios
    displayName: Obtener usuarios
    is:
      - hasHeaders
      - responses
    responses:
      200:
        description: OK
        body:
          application/json:
            example: !include examples/usuarios/usuarios-get.json
  post:
    description: Crear usuarios
    displayName: Crear usuarios
    body:
      application/json:
        type: !include examples/datatype/usuarios-dataType.raml
        example: !include examples/datatype/usuarios-post.json
    is:
      - hasHeaders
      - responses
    responses:
      201:
        description: CREATED
        body:
          application/json:
            example: !include examples/usuarios/usuarios-post.json
  /{id}:
    delete:
      description: Elimina usuarios
      displayName: Eliminar usuarios
      is:
        - hasHeaders
        - responses
      responses:
        200:
          description: OK
          body:
            application/json:
              example: {
                "message" : "Eliminado"
              }

/admin:
  displayName: Panel Admin
  description: Iniciar sesion para el administrador
  is:
    - hasHeaders
    - responses
  post:
    displayName: Iniciar sesion
    description: Iniciar sesion para el administrador
    body:
      application/json:
        example: {
          Nombre : "urias",
          Contrasena : "urias"
        }
    responses:
      200:
        description: OK
        body:
          application/json:
            example: {
              "logged" : true
            }